server.port=8080
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB

spring.datasource.url=${DOGLOG_DB_URL:jdbc:h2:file:./data/doglog;MODE=MySQL;DATABASE_TO_LOWER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE}
spring.datasource.username=${DOGLOG_DB_USERNAME:sa}
spring.datasource.password=${DOGLOG_DB_PASSWORD:}
spring.datasource.driver-class-name=${DOGLOG_DB_DRIVER:org.h2.Driver}

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.continue-on-error=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true
server.servlet.encoding.force=true
