CREATE TABLE IF NOT EXISTS APP_USER (
    userID VARCHAR(50) PRIMARY KEY,
    userPassword VARCHAR(100) NOT NULL,
    userEmail VARCHAR(255),
    userGender VARCHAR(20),
    userType VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS DOG (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    breed VARCHAR(100) NOT NULL,
    age INT NOT NULL DEFAULT 0,
    status VARCHAR(100) NOT NULL,
    fosterId VARCHAR(50) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS DIARY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fosterId VARCHAR(50) NOT NULL DEFAULT '',
    dogName VARCHAR(100) NOT NULL,
    dateText VARCHAR(30) NOT NULL,
    foodAmount INT NOT NULL,
    poopCount INT NOT NULL,
    content TEXT NOT NULL,
    photoData TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
